tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "bitwarden-cli"
brew "chezmoi"
brew "git"
brew "gnupg"
brew "mas"
brew "n"
brew "pinentry-mac"
brew "youtube-dl"
cask "alfred"
cask "appcleaner"
cask "bitwarden"
cask "blobsaver"
cask "boop"
cask "discord"
cask "eloston-chromium"
cask "github"
cask "google-drive"
cask "hiddenbar"
cask "iina"
cask "karabiner-elements"
cask "notion"
cask "plex"
cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "sound-control"
cask "synology-drive"
cask "telegram"
cask "tor-browser"
cask "tunnelblick"
cask "visual-studio-code"
cask "webtorrent"
cask "whatsapp"
mas "Gifski", id: 1351639930
mas "iStudiez Pro", id: 402989379
mas "Notability", id: 360593530
mas "Plash", id: 1494023538
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Xcode", id: 497799835
